name: Publish Antora Site

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        repository: yocurt/docs
        ref: master
    - name: Copy to workspace
      run: |
        rm -rf $GITHUB_WORKSPACE
        mv ../docs $GITHUB_WORKSPACE
    - name: Generate Antora Site
      uses: jsqu4re/antora_build@0.1.1
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.4
      with:
        repo: yocurt/docs
        target_branch: gh-pages
        keep_history: true
        allow_empty_commit: true
        build_dir: build/site
        committer_name: "Update Pages"
        committer_email: update@github.pages
        commit_message: "update gh pages"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
